"""Phase 1.5 Additions

Revision ID: 1956dc1a5fa5
Revises: 16ad360d2153
Create Date: 2026-06-05 14:38:27.543822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1956dc1a5fa5'
down_revision: Union[str, Sequence[str], None] = '16ad360d2153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audience_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_snapshots_id'), 'audience_snapshots', ['id'], unique=False)
    op.create_table('trend_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_snapshots_id'), 'trend_snapshots', ['id'], unique=False)
    op.create_table('recommendation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_history_id'), 'recommendation_history', ['id'], unique=False)
    op.add_column('recommendations', sa.Column('audience_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('historical_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('trend_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('competition_score', sa.Float(), nullable=True))
    op.add_column('recommendations', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('related_videos', sa.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('related_comments', sa.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('related_trends', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'related_trends')
    op.drop_column('recommendations', 'related_comments')
    op.drop_column('recommendations', 'related_videos')
    op.drop_column('recommendations', 'evidence')
    op.drop_column('recommendations', 'competition_score')
    op.drop_column('recommendations', 'trend_score')
    op.drop_column('recommendations', 'historical_score')
    op.drop_column('recommendations', 'audience_score')
    op.drop_index(op.f('ix_recommendation_history_id'), table_name='recommendation_history')
    op.drop_table('recommendation_history')
    op.drop_index(op.f('ix_trend_snapshots_id'), table_name='trend_snapshots')
    op.drop_table('trend_snapshots')
    op.drop_index(op.f('ix_audience_snapshots_id'), table_name='audience_snapshots')
    op.drop_table('audience_snapshots')
    # ### end Alembic commands ###
