"""Add phase 2 tables

Revision ID: 24a71f5ac71f
Revises: 1956dc1a5fa5
Create Date: 2026-06-05 14:57:04.099044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a71f5ac71f'
down_revision: Union[str, Sequence[str], None] = '1956dc1a5fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('video_goal', sa.String(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('content_angle', sa.String(), nullable=True),
    sa.Column('competitor_reference', sa.JSON(), nullable=True),
    sa.Column('estimated_length', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_briefs_id'), 'content_briefs', ['id'], unique=False)
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.Column('hook', sa.String(), nullable=True),
    sa.Column('introduction', sa.String(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('cta', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['content_briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scripts_id'), 'scripts', ['id'], unique=False)
    op.create_table('storyboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('scenes', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboards_id'), 'storyboards', ['id'], unique=False)
    op.create_table('generated_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_assets_id'), 'generated_assets', ['id'], unique=False)
    op.create_table('generated_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_videos_id'), 'generated_videos', ['id'], unique=False)
    op.create_table('generation_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=True),
    sa.Column('prompt_type', sa.String(), nullable=True),
    sa.Column('prompt_text', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_prompts_id'), 'generation_prompts', ['id'], unique=False)
    op.create_table('publish_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('youtube_video_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['generated_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publish_history_id'), 'publish_history', ['id'], unique=False)
    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('variant_name', sa.String(), nullable=True),
    sa.Column('ab_test_winner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['generated_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnails_id'), 'thumbnails', ['id'], unique=False)
    op.create_table('video_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['generated_videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_metadata_id'), 'video_metadata', ['id'], unique=False)
    op.create_table('prediction_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_id', sa.Integer(), nullable=True),
    sa.Column('predicted_views', sa.Integer(), nullable=True),
    sa.Column('actual_views', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['publish_id'], ['publish_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_accuracy_id'), 'prediction_accuracy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_accuracy_id'), table_name='prediction_accuracy')
    op.drop_table('prediction_accuracy')
    op.drop_index(op.f('ix_video_metadata_id'), table_name='video_metadata')
    op.drop_table('video_metadata')
    op.drop_index(op.f('ix_thumbnails_id'), table_name='thumbnails')
    op.drop_table('thumbnails')
    op.drop_index(op.f('ix_publish_history_id'), table_name='publish_history')
    op.drop_table('publish_history')
    op.drop_index(op.f('ix_generation_prompts_id'), table_name='generation_prompts')
    op.drop_table('generation_prompts')
    op.drop_index(op.f('ix_generated_videos_id'), table_name='generated_videos')
    op.drop_table('generated_videos')
    op.drop_index(op.f('ix_generated_assets_id'), table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_index(op.f('ix_storyboards_id'), table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index(op.f('ix_scripts_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_content_briefs_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    # ### end Alembic commands ###
