"""add_content_type_to_videos_and_recs

Revision ID: e1601c3ee2e7
Revises: 0e307dc16803
Create Date: 2026-06-06 17:32:40.531752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1601c3ee2e7'
down_revision: Union[str, Sequence[str], None] = '0e307dc16803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('recommendations', sa.Column('content_type', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('content_type', sa.String(), nullable=True))
    op.execute("UPDATE recommendations SET content_type = 'LONG_FORM'")
    op.execute("UPDATE videos SET content_type = 'LONG_FORM'")
    op.alter_column('recommendations', 'content_type', nullable=False)
    op.alter_column('videos', 'content_type', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'content_type')
    op.drop_column('recommendations', 'content_type')
    # ### end Alembic commands ###
