"""Add voiceover and subtitle tables

Revision ID: f6d8581a0b0a
Revises: 24a71f5ac71f
Create Date: 2026-06-05 18:31:20.697078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d8581a0b0a'
down_revision: Union[str, Sequence[str], None] = '24a71f5ac71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_id'), 'subtitles', ['id'], unique=False)
    op.create_table('voiceovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storyboard_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voiceovers_id'), 'voiceovers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voiceovers_id'), table_name='voiceovers')
    op.drop_table('voiceovers')
    op.drop_index(op.f('ix_subtitles_id'), table_name='subtitles')
    op.drop_table('subtitles')
    # ### end Alembic commands ###
